// <auto-generated />
namespace OnlineExams.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class New_Property_add_in_Trainer_For_Image : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New_Property_add_in_Trainer_For_Image));
        
        string IMigrationMetadata.Id
        {
            get { return "201809081953216_New_Property_add_in_Trainer_For_Image"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
