// <auto-generated />
namespace OnlineExam.DataContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Change_ExamdurationType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_ExamdurationType));
        
        string IMigrationMetadata.Id
        {
            get { return "201809281914367_Change_ExamdurationType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
